<?php
$z[0]=Array("starttime","",122,140);
$z[0][4]=array();
$z[1]=Array("endtime","",144,160);
$z[1][4]=array();
$z[2]=Array("pubdate","",171,220);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%Y/%m\",@me)";
$z[3]=Array("arcurl","",282,297);
$z[3][4]=array();
$z[4]=Array("title","",299,313);
$z[4][4]=array();
$z[5]=Array("infos","",369,383);
$z[5][4]=array();
$z[6]=Array("litpic","",661,676);
$z[6][4]=array();

?>