
<field:name itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>










<field:phone itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:sex itemname="性别" autofield="1" type="select" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:email itemname="电子邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>


<field:con itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:con>
