<div class="col-md-12 ny-list">
                       <div class="col-md-1 hidden-xs date">
                           <span>[field:pubdate function='strftime("%Y/%m",@me)'/]</span>
                           <h2>[field:pubdate function='strftime("%d",@me)'/]</h2>
                       </div>
                       <div class="col-md-10 col-xs-12 news">
                           <div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
                           <div class="nr">[field:infos/] ...</div>
                       </div>
                   </div>