<?php
$z[0]=Array("field","",27,55);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",57,86);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n                <li>\r\n                   <a href=\"=\"[field:arcurl /]\" target=\"\"><strong>[field:title /]</strong></a>\r\n                </li>\r\n                ",145,356);
$z[2][4]=array();
$z[2][4]['titlelen']="42";
$z[2][4]['row']="15";

?>