<?php
$z[0]=Array("field","",13,41);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",55,84);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",140,163);
$z[2][4]=array();
$z[2][4]['name']="seotitle";
$z[3]=Array("channel"," \r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                 ",250,404);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="true";

?>