
<field:name itemname="您的姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:email itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>


<field:sex itemname="性别" autofield="1" type="select" isnull="true" default="男,女"  maxlength="250" page="">
</field:sex>

<field:title itemname="留言标题" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:title>

<field:con itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:con>
