<li>
            <a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
     <!--          <div class="pro_thr">
                {dede:arclist titlelen='42' row='15'}
                <li style="border-bottom:1px dashed #666; padding: 2%; margin-top: 3%; width: 98%;">
                   <a href="="[field:arcurl /]" target=""><strong>[field:title /]</strong></a>
                </li>
                {/dede:arclist}
              </div> -->
          </li>