<div class="col-md-12 list-bk">
                        <div class="col-md-6">
                            <div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
                            <span class="bqian"><i class="iconfont icon-biaoqian"></i>&nbsp;古典园林&nbsp;&nbsp;异域风情&nbsp;&nbsp;美轮美奂&nbsp;&nbsp;&nbsp;<i class="iconfont icon-huiyuan"></i>&nbsp;适合历史爱好者游玩</span>
                            <div class="zw">[field:infos/] ...</div>
                            <button type="button" class="btn btn-primary" style="margin-bottom: 5%;">&nbsp;&nbsp;查看详情&nbsp;&nbsp; </button>
                             <button type="button" class="btn btn-warning" style="margin-bottom: 5%;">&nbsp;&nbsp;地理位置&nbsp;&nbsp; </button>
                        </div>
                        <div class="col-md-6">
                           <img src="[field:litpic/]" alt="">
                        </div>
                    </div>