
<field:pic1 itemname="缩略图1" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic1>

<field:pic2 itemname="缩略图2" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic2>

<field:pic3 itemname="缩略图3" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic3>
