<?php
$z[0]=Array("field","",41,69);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",83,112);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",149,172);
$z[2][4]=array();
$z[2][4]['name']="seotitle";
$z[3]=Array("channel"," \r\n                    <li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n                 ",259,413);
$z[3][4]=array();
$z[3][4]['type']="son";
$z[3][4]['noself']="true";

?>