
<field:startTime itemname="开始时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:startTime>

<field:endTime itemname="结束时间" autofield="1" notsend="0" type="datetime" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:endTime>

<field:newContent itemname="新闻内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:newContent>
