<div class="col-md-12 bk">
                        <div class="col-md-6">
                            <div class="date">2018-9-10 至 2018-10-10</div><!-- [field:pubdate function='strftime("%Y/%m",@me)'/] -->
                            <div class="title"><a href="[field:arcurl/]">[field:title/]</a></div>
                            <div class="zw">[field:infos/] ...</div>
                            <button type="button" class="btn btn-primary" style="margin-bottom: 5%;">&nbsp;&nbsp;查看详情&nbsp;&nbsp; </button>
                        </div>
                        <div class="col-md-6">
                           <img src="[field:litpic/]" alt="">
                        </div>
                    </div>