<field:pic1 itemname="缩略图1" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic1>

<field:pic2 itemname="缩略图2" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic2>

<field:pic3 itemname="缩略图3" autofield="1" notsend="0" type="img" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic3>

<field:pic4 itemname="缩略图4" autofield="1" notsend="0" type="addon" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:pic4>

<field:daolanKey itemname="关键字" autofield="1" notsend="0" type="textchar" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:daolanKey>

<field:wznr itemname="文章内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:wznr>
