<?php
$z[0]=Array("field","",31,59);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",86,115);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n                    <li><a href=\"[field:typelink/]\" style=\"color: #000\">[field:typename/]</a></li>\r\n                    ",167,344);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="true";

?>