[field:typename/]}<br /><span style="font-size: 10px;">{dede:field.seotitle /}</span>{/dede:type</a>
        <ul class="menu">
        {dede:channel type='son' typeid='10' titlelen='30'}
          <li><a href="[field:typeurl/]">[field:typename/]</a></li>
          {/dede:channel}
        </ul>
    </li>
    <li><a href="#">{dede:type typeid='20'}[field:typename/]<br /><span style="font-size: 10px;">{dede:field.seotitle /}</span>