<tr>
                        <td><a href="[field:arcurl/]" >[field:title/]</a></td>
                        <td>[field:zwlx/]</td>
                        <td>[field:zwyq/]</td>
                        <td>[field:age/]</td>
                        <td><a href="mailto:youemail@mail.com" style="padding: 2% 5% 2% 5%;background:#25B5FC; color: #fff;border-radius: 5%;">点击发送简历</a></td>
                      </tr>