<li ><a href="{dede:field name='typeurl'/}"><br /><span>{dede:field name='typename'/}<br /><span style="font-size: 10px;">{dede:field.seotitle /}</span></a>
                
                <ul class="hidden-xs">
                {dede:channel type='son' noself='true'} 
                    <li><a href="[field:typelink/]">[field:typename/]</a></li>
                 {/dede:channel} 
                </ul>
                
            </li>