<?php
$z[0]=Array("starttime","",132,150);
$z[0][4]=array();
$z[1]=Array("endtime","",154,170);
$z[1][4]=array();
$z[2]=Array("pubdate","",181,230);
$z[2][4]=array();
$z[2][4]['function']="strftime(\"%Y/%m\",@me)";
$z[3]=Array("arcurl","",292,307);
$z[3][4]=array();
$z[4]=Array("title","",309,323);
$z[4][4]=array();
$z[5]=Array("infos","",379,393);
$z[5][4]=array();
$z[6]=Array("litpic","",671,686);
$z[6][4]=array();

?>