<?php
$z[0]=Array("field","",13,41);
$z[0][4]=array();
$z[0][4]['name']="typeurl";
$z[1]=Array("field","",55,84);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("channel"," \r\n                <ul class=\"hidden-xs\">\r\n                    <li><a href=\"[field:typelink/]\"> </a>[field:typename/]</li>\r\n                </ul>\r\n                 ",130,348);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['noself']="true";

?>