<div class="col-md-12 bk">
                        <div class="col-md-6">
                            <div class="date">2018-9-10 至 2018-10-10</div><!-- [field:pubdate function='strftime("%Y/%m",@me)'/] -->
                            <div class="title">[field:title/]</div>
                            <div class="zw">[field:infos/] ...</div>
                            <button type="button" class="btn btn-primary">&nbsp;&nbsp;查看详情&nbsp;&nbsp; </button>
                        </div>
                        <div class="col-md-6"><img src="{dede:global.cfg_templets_skin/}/images/new-jxz.jpg"  alt=""></div>
                    </div>