<li><a href="[field:arcurl/]"><span>{dede:field.pubdate function="MyDate('Y-m-d',@me)"/}</span>[field:title/]</a></li>
        <!--     <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
            <li><a href="#"><span>2018-05-07</span>新闻标题新闻标题新闻标题新闻标题</a></li>
 -->