<?php
$z[0]=Array("channelartlist","\r\n            <li>\r\n                <a href=\"{dede:field name='typeurl'/}\" style=\"color: #fff;\" ><b>{dede:field name='typename'/}</b></a>\r\n                <ul>\r\n                    {dede:channel type='son' noself='true'} \r\n                    <li><a href=\"[field:typelink/]\" style=\"color: #666\">[field:typename/]</a></li>\r\n                    {/dede:channel} \r\n                </ul>\r\n            </li>\r\n        ",96,571);
$z[0][4]=array();
$z[0][4]['row']="9";
$z[0][4]['typeid']="top";
$z[1]=Array("global","",644,676);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";

?>