<?php
$z[0]=Array("global","",222,254);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",502,534);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",597,629);
$z[2][4]=array();
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",1484,1516);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("channelartlist","\r\n                    <li>\r\n                        <a href=\"{dede:field name='typeurl'/}\" style=\"color: #000;\" >{dede:field name='typename'/}</a>\r\n                        <ul>\r\n                            {dede:channel type='son' noself='true'} \r\n                            <li><a href=\"[field:typelink/]\" style=\"color: #000\">[field:typename/]</a></li>\r\n                            {/dede:channel} \r\n                        </ul>\r\n                    </li>\r\n                  ",1777,2319);
$z[4][4]=array();
$z[4][4]['row']="9";
$z[4][4]['typeid']="top";

?>