<?php
$z[0]=Array("global","",159,191);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channelartlist","\r\n                    <li>\r\n                        <a href=\"{dede:field name='typeurl'/}\" style=\"color: #000;\" >{dede:field name='typename'/}</a>\r\n                        <ul>\r\n                            {dede:channel type='son' noself='true'} \r\n                            <li><a href=\"[field:typelink/]\" style=\"color: #000\">[field:typename/]</a></li>\r\n                            {/dede:channel} \r\n                        </ul>\r\n                    </li>\r\n                  ",452,994);
$z[1][4]=array();
$z[1][4]['row']="9";
$z[1][4]['typeid']="top";

?>