<?php
$z[0]=Array("global","",72,97);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",110,142);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",165,191);
$z[2][4]=array();
$z[2][4]['name']="cfg_webname";
$z[3]=Array("global","",356,381);
$z[3][4]=array();
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("channelartlist","\n					<li class=\"m\">\n						<h3><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}<br /><span>{dede:field.seotitle /}</span></a></h3></li>\n					",440,680);
$z[4][4]=array();
$z[4][4]['row']="9";
$z[4][4]['typeid']="1,2,3,4,5,6,7,8,9";

?>