<?php
$z[0]=Array("global","",76,101);
$z[0][4]=array();
$z[0][4]['name']="cfg_cmsurl";
$z[1]=Array("global","",114,146);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",169,196);
$z[2][4]=array();
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("global","",235,259);
$z[3][4]=array();
$z[3][4]['name']="cfg_phone";
$z[4]=Array("global","",401,426);
$z[4][4]=array();
$z[4][4]['name']="cfg_cmsurl";
$z[5]=Array("channelartlist","\n				<li class=\"m\">\n					<h3><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h3></li>\n				",459,648);
$z[5][4]=array();
$z[5][4]['row']="6";
$z[5][4]['typeid']="1,2,3,4,5,6";

?>