<?php
$z[0]=Array("global","",89,113);
$z[0][4]=array();
$z[0][4]['name']="cfg_phone";
$z[1]=Array("global","",156,180);
$z[1][4]=array();
$z[1][4]['name']="cfg_email";
$z[2]=Array("global","",258,283);
$z[2][4]=array();
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",296,328);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",351,378);
$z[4][4]=array();
$z[4][4]['name']="cfg_keywords";
$z[5]=Array("channelartlist","\n					<li class=\"m\">\n						<h3><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></h3></li>\n					",495,691);
$z[5][4]=array();
$z[5][4]['row']="8";
$z[5][4]['typeid']="1,2,3,4,5,6,7,8";

?>