<?php
$z[0]=Array("global","",120,152);
$z[0][4]=array();
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("channel","\r\n			    	<li><a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n			    ",967,1095);
$z[1][4]=array();
$z[1][4]['typeid']="2";
$z[1][4]['type']="son";
$z[2]=Array("channelartlist","\r\n		<li><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li>\r\n		",1121,1279);
$z[2][4]=array();
$z[2][4]['row']="7";
$z[2][4]['typeid']="1,3,5,6";
$z[3]=Array("global","",2005,2037);
$z[3][4]=array();
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2203,2235);
$z[4][4]=array();
$z[4][4]['name']="cfg_templets_skin";

?>