<?php
$z[0]=Array("channel","\r\n            <li class=\"fdh\"><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></li>\r\n        ",166,421);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['row']="6";
$z[0][4]['titlelen']="30";
$z[0][4]['currentstyle']="<li class='hover'><a href='~typelink~'><span>~typename~</span></a></li>";
$z[1]=Array("global","",507,539);
$z[1][4]=array();
$z[1][4]['name']="cfg_templets_skin";

?>