<?php
$z[0]=Array("type","<a href=\"[field:typelink /]\">[field:typename/]<i class=\"bangong_zt\">&#xe646;</i></a>",60,179);
$z[0][4]=array();
$z[0][4]['typeid']="11";
$z[1]=Array("channel","\r\n						<li><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\n						",196,334);
$z[1][4]=array();
$z[1][4]['type']="son";
$z[1][4]['typeid']="11";
$z[1][4]['titlelen']="30";
$z[2]=Array("channelartlist","\n				<li>\n					<a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\n				</li>\n				",361,567);
$z[2][4]=array();
$z[2][4]['row']="14";
$z[2][4]['typeid']="12,13,14,15,16,17,18,19,20,21,22,23,24,25";

?>